// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5RPzfaYxZ2yhz89q34JH1Se6g2R0plkY',
    appId: '1:27518104679:web:e6e301f5bcd6653cac50c2',
    messagingSenderId: '27518104679',
    projectId: 'innergames2',
    authDomain: 'innergames2.firebaseapp.com',
    storageBucket: 'innergames2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATBQC_4pXrbahWzRqI1T7n_vnEZ1jViII',
    appId: '1:27518104679:android:b13aa9ddf1cf7dd4ac50c2',
    messagingSenderId: '27518104679',
    projectId: 'innergames2',
    storageBucket: 'innergames2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_2icQR5PviHH4YIF-Sf50QuGY5eCA7U',
    appId: '1:27518104679:ios:bdc54aafa912ed54ac50c2',
    messagingSenderId: '27518104679',
    projectId: 'innergames2',
    storageBucket: 'innergames2.firebasestorage.app',
    iosBundleId: 'com.tweekracht.tweekrachtSociality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc_2icQR5PviHH4YIF-Sf50QuGY5eCA7U',
    appId: '1:27518104679:ios:bdc54aafa912ed54ac50c2',
    messagingSenderId: '27518104679',
    projectId: 'innergames2',
    storageBucket: 'innergames2.firebasestorage.app',
    iosBundleId: 'com.tweekracht.tweekrachtSociality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5RPzfaYxZ2yhz89q34JH1Se6g2R0plkY',
    appId: '1:27518104679:web:dd797cf365c438c6ac50c2',
    messagingSenderId: '27518104679',
    projectId: 'innergames2',
    authDomain: 'innergames2.firebaseapp.com',
    storageBucket: 'innergames2.firebasestorage.app',
  );
}
